In [1]:
using BenchmarkTools

In [9]:
function matmul(a, b)
    c = zeros(size(a)[1], size(b)[2])
    
    for j = 1:size(b)[2]
        for i = 1:size(a)[1]
            for k = 1:size(a)[2]
                c[i,j] +=  a[i,k]*b[k,j]
            end
        end
    end
            
    return c
end

matmul (generic function with 1 method)

In [16]:
l = 2000
m = 3000
n = 1000
a = rand(l, n)
b = rand(n, m)

@time matmul(a, b)

  9.672299 seconds (2 allocations: 45.776 MiB, 6.42% gc time)


2000×3000 Matrix{Float64}:
 253.504  252.321  255.497  241.19   …  255.902  238.886  255.043  242.811
 257.59   259.61   265.152  256.726     249.818  254.255  254.459  249.059
 249.915  251.622  247.529  244.339     240.68   240.203  245.933  244.144
 253.831  259.956  249.944  257.524     246.792  250.073  256.082  247.147
 256.097  258.574  259.333  252.558     253.1    250.167  257.103  252.137
 245.36   243.921  250.481  245.485  …  245.744  244.625  250.172  241.989
 248.254  255.931  257.508  249.372     247.511  246.796  251.549  246.054
 250.719  260.299  255.732  251.398     252.41   245.38   249.922  250.357
 248.108  247.109  252.075  245.979     247.613  240.494  250.942  245.268
 248.329  252.788  249.988  246.861     244.858  246.263  249.883  242.807
 246.82   245.078  249.128  237.549  …  247.015  238.297  246.801  244.345
 255.703  259.23   257.808  251.937     250.507  250.104  251.85   250.641
 255.96   260.669  256.566  252.73      259.354  247.751  261.768  250.23

In [17]:
@time a*b

  0.191336 seconds (2 allocations: 45.776 MiB, 35.68% gc time)


2000×3000 Matrix{Float64}:
 253.504  252.321  255.497  241.19   …  255.902  238.886  255.043  242.811
 257.59   259.61   265.152  256.726     249.818  254.255  254.459  249.059
 249.915  251.622  247.529  244.339     240.68   240.203  245.933  244.144
 253.831  259.956  249.944  257.524     246.792  250.073  256.082  247.147
 256.097  258.574  259.333  252.558     253.1    250.167  257.103  252.137
 245.36   243.921  250.481  245.485  …  245.744  244.625  250.172  241.989
 248.254  255.931  257.508  249.372     247.511  246.796  251.549  246.054
 250.719  260.299  255.732  251.398     252.41   245.38   249.922  250.357
 248.108  247.109  252.075  245.979     247.613  240.494  250.942  245.268
 248.329  252.788  249.988  246.861     244.858  246.263  249.883  242.807
 246.82   245.078  249.128  237.549  …  247.015  238.297  246.801  244.345
 255.703  259.23   257.808  251.937     250.507  250.104  251.85   250.641
 255.96   260.669  256.566  252.73      259.354  247.751  261.768  250.23

In [12]:
@benchmark matmul(a, b)

BenchmarkTools.Trial: 850 samples with 1 evaluation.
 Range (min … max):  5.786 ms …   8.855 ms  ┊ GC (min … max): 0.00% … 33.60%
 Time  (median):     5.857 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   5.879 ms ± 213.219 μs  ┊ GC (mean ± σ):  0.34% ±  2.57%

      ▃▄▆▄▄▅█▇█▆▅▃▃                                            
  ▂▁▃███████████████▅▃▄▃▂▃▃▂▂▁▂▂▁▁▂▁▁▁▁▁▂▂▁▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▂ ▄
  5.79 ms         Histogram: frequency by time        6.16 ms <

 Memory estimate: 468.80 KiB, allocs estimate: 2.

In [13]:
@benchmark a*b

BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  181.209 μs …   9.336 ms  ┊ GC (min … max):  0.00% … 96.37%
 Time  (median):     258.583 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):   284.966 μs ± 306.202 μs  ┊ GC (mean ± σ):  10.10% ±  9.14%

    █▅                                                           
  ▂▇██▃▂▂▂▁▂▁▁▁▁▁▁▂▂▁▁▁▁▁▁▁▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▂▂▁▂ ▂
  181 μs           Histogram: frequency by time         1.78 ms <

 Memory estimate: 468.80 KiB, allocs estimate: 2.

In [3]:
c = similar(a)

2×2 Matrix{Int64}:
 0  0
 0  0

In [4]:
size(c)

(2, 2)

In [18]:
using PyPlot

LoadError: ArgumentError: Package PyPlot not found in current path.
- Run `import Pkg; Pkg.add("PyPlot")` to install the PyPlot package.