In [31]:
using BenchmarkTools

In [32]:
function matmul(a, b)
    c = zeros(size(a)[1], size(b)[2])
    
    for j = 1:size(a)[1]
        for i = 1:size(b)[2]
            for k = 1:size(a)[2]
                c[i,j] +=  a[i,k]*b[k,j]
            end
        end
    end
            
    return c
end

matmul (generic function with 1 method)

In [33]:
a = rand(100, 100)
b = rand(100, 100)

matmul(a, b)

100×100 Matrix{Float64}:
 25.6102  21.8515  23.9676  23.4915  …  26.1134  24.1268  25.2904  24.205
 25.2127  20.9826  22.9318  23.3809     23.5178  22.2649  21.2027  21.4591
 29.531   22.5138  25.9329  25.3842     25.8763  27.692   25.338   25.4027
 25.9094  22.3302  23.0524  23.2392     25.0042  26.3689  22.4425  23.1695
 27.8801  21.7247  23.4681  24.7004     25.2819  27.2175  23.9225  24.5974
 25.4586  20.6463  22.4525  23.5515  …  25.586   25.382   22.2884  24.389
 26.3551  22.9882  23.1053  24.2526     24.138   24.3362  22.7055  24.1983
 23.5013  20.7841  21.9117  23.343      23.3929  22.9307  21.4137  21.1103
 27.117   22.2765  24.5216  22.9336     25.7094  25.7636  22.5976  24.0878
 27.4612  24.8479  24.9909  24.5582     27.6571  26.959   26.5403  25.0537
 25.5747  21.8004  24.2023  21.5378  …  25.4185  26.0771  24.1434  23.4658
 28.8425  25.2144  25.1642  26.3968     27.912   27.9259  25.8881  26.0417
 26.7242  22.5655  23.5977  22.8753     24.5068  26.7318  24.4672  23.6468
  

false

In [34]:
a*b

100×100 Matrix{Float64}:
 25.6102  21.8515  23.9676  23.4915  …  26.1134  24.1268  25.2904  24.205
 25.2127  20.9826  22.9318  23.3809     23.5178  22.2649  21.2027  21.4591
 29.531   22.5138  25.9329  25.3842     25.8763  27.692   25.338   25.4027
 25.9094  22.3302  23.0524  23.2392     25.0042  26.3689  22.4425  23.1695
 27.8801  21.7247  23.4681  24.7004     25.2819  27.2175  23.9225  24.5974
 25.4586  20.6463  22.4525  23.5515  …  25.586   25.382   22.2884  24.389
 26.3551  22.9882  23.1053  24.2526     24.138   24.3362  22.7055  24.1983
 23.5013  20.7841  21.9117  23.343      23.3929  22.9307  21.4137  21.1103
 27.117   22.2765  24.5216  22.9336     25.7094  25.7636  22.5976  24.0878
 27.4612  24.8479  24.9909  24.5582     27.6571  26.959   26.5403  25.0537
 25.5747  21.8004  24.2023  21.5378  …  25.4185  26.0771  24.1434  23.4658
 28.8425  25.2144  25.1642  26.3968     27.912   27.9259  25.8881  26.0417
 26.7242  22.5655  23.5977  22.8753     24.5068  26.7318  24.4672  23.6468
  

In [35]:
@benchmark matmul(a, b)

BenchmarkTools.Trial: 4983 samples with 1 evaluation.
 Range (min … max):  967.333 μs …  12.345 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     982.917 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.001 ms ± 262.330 μs  ┊ GC (mean ± σ):  0.36% ± 2.72%

    ▁▆█▅                                                         
  ▃▆██████▇▆▅▄▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▁▁▂▂▁▁▂▂▂▁▂▂▂▁▂▂▂▁▂ ▃
  967 μs           Histogram: frequency by time         1.15 ms <

 Memory estimate: 78.17 KiB, allocs estimate: 2.

In [36]:
@benchmark a*b

BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  56.250 μs … 977.959 μs  ┊ GC (min … max): 0.00% … 91.44%
 Time  (median):     63.875 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   64.978 μs ±  32.311 μs  ┊ GC (mean ± σ):  1.97% ±  3.70%

         ▁            ▁▅▆█▃                                     
  ▂▂▃▃▄▅██▇▄▃▃▃▃▂▃▃▃▄▅██████▇▅▅▆▆▆▆▄▃▃▃▂▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂ ▃
  56.2 μs         Histogram: frequency by time         76.2 μs <

 Memory estimate: 78.17 KiB, allocs estimate: 2.

In [3]:
c = similar(a)

2×2 Matrix{Int64}:
 0  0
 0  0

In [4]:
size(c)

(2, 2)